### ISSUE TITLE
Invalid filename: 1-activity.png.png

### ISSUE THREAD

**Issue by cobookman** [googlesamples/android-ActionBarCompat-Styled#1]
https://github.com/googlesamples/android-ActionBarCompat-Styled/blob/master/screenshots/1-activity.png.png

filename needs changing from `1-activity.png.png` to `1-activity.png`
https://github.com/googlesamples/android-ActionBarCompat-Styled/blob/master/screenshots/1-activity.png

**Comment by keyboardsurfer** [comment]
Internal: 26503965

**Comment by thagikura** [comment]
Fixed the issue in the internal repo. It will be reflected in this repo soon.
